version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: dockerfile_db
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
      
 web:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
